### ISSUE TITLE
Prizes saved wrong

### ISSUE THREAD

**Issue by Celelibi** [Neo-Coder-usa/super-duckhunt-beta#1]
Hello,

I just want to point out that the prizes Silencer and Sunglasses are saved as `accident_insurance` instead of `silencer` and `sunglasses`.
https://github.com/Neo-Coder-usa/super-duckhunt-beta/blob/0e5c298c977a812aa5704889a92cbe3106864fcb/main.py#L419-L438

Should be an easy fix.

Best regards,
Celelibi

**Comment by Neo-Coder-usa** [comment]
Thank you. That has been fixed for the upcoming update. The entire prize line up has changed ;) and a lot of other stuff and fixes. Keep an eye out for the update. Should be in a couple days. HOPEFULLY.

**Comment by m0de-60** [comment]
Thank you. That has been fixed for the upcoming update. The entire prize line up has changed ;) and a lot of other stuff and fixes. Keep an eye out for the update. Should be in a couple days. HOPEFULLY.
