### ISSUE TITLE
After update on 4-1-24, the bot will not boot. 

### ISSUE THREAD

**Issue by lord3nd3r** [Neo-Coder-usa/super-duckhunt-beta#2]
b'DATA RECV: :*.freenode.net 372 DuckHunt :  #chanhelp                - Help with channels and channel services.'
b'DATA RECV: :*.freenode.net 372 DuckHunt :  #IRC                     - Help with the IRC.com by freenode app.'
b'DATA RECV: :*.freenode.net 372 DuckHunt : '
b'DATA RECV: :*.freenode.net 372 DuckHunt :  Checkout some of our communities and services:'
b'DATA RECV: :*.freenode.net 372 DuckHunt : '
b'DATA RECV: :*.freenode.net 372 DuckHunt :  #freenode-bbs            - BBS [https://bbs.freenode.net/]'
b'DATA RECV: :*.freenode.net 372 DuckHunt :  #freenode-bbs-discussion - BBS Discussion'
b'DATA RECV: :*.freenode.net 372 DuckHunt :  #freenode-jobs           - Jobs [https://jobs.freenode.net/]'
b'DATA RECV: :*.freenode.net 372 DuckHunt :  #freenode                - Chat about freenode'
b'DATA RECV: .'
Traceback (most recent call last):
  File "/home/ender/super-duckhunt-beta/main.py", line 1002, in <module>
    if data[1] == b'PONG':
       ~~~~^^^
IndexError: list index out of range

**Comment by m0de-60** [comment]
Fix posted
