### ISSUE TITLE
Set the bot modes properly before joining the channel

### ISSUE THREAD

**Issue by marthellius** [Neo-Coder-usa/super-duckhunt-beta#3]
There are many IRC channels that send their recent chat history upon joining. This can typically be found on InspIRCd servers that  have the chanhistory module enabled, though it can probably be found on other IRC servers too.

So when you join a channel with history enabled, you receive immediately the last n lines that were typed on it. Sometimes there are just a few lines, and other times there can be a lot of them going back several hours (depending on channel activity and how the ops or owners have set it up).

Now, when a bot joins such a channel and it receives all the recent history, those previous messages could trigger many bot actions leading to undesired efects (for example, multiple !bang commands that would  be replayed and obviously would miss because there are no ducks flying when the bot starts). 

Adding logic for ignoring previous messages when joining a channel can be unreliable and quite tricky. But fortunately there's an easy fix for this: **set the bot mode to +N just before it joins the channel**.  N stands for **nohistory**, and it does what the name implies: the bot will get no history when joining, and so no previous actions will be replayed when it starts.

This can be done after the following block in main.py:

``` 
    if data[1] == b'376':
        isconnect = True
        if str(botpass) != '0':
            irc.send(b'PRIVMSG ' + b'NickServ :IDENTIFY ' + bytes(str(botpass), 'utf-8') + b'\r\n')
```

by adding this:

`        irc.send(b"MODE " + botname + b" +N\r\n")`

Of course this is just a quick hack. Ideally you should have an extra setting for the bot modes in duckhunt.cnf, and then read that setting dynamically when the bot is run. For example:

`botmodes = +N`

BTW, you'll probably also want mode -c, which disables the deaf_commomchan mode on IRC servers that have it enabled. This allows you to message the bot privately even if you're not on the same channel, which can be quite useful (specially for the botmaster).

**Comment by m0de-60** [comment]
This is something I've considered but honestly got put on the back burner. This will be something implemented in the final update.
