### ISSUE TITLE
Make color attributes customizable

### ISSUE THREAD

**Issue by marthellius** [Neo-Coder-usa/super-duckhunt-beta#4]
Right now all the color attributes used in messages sent by the bot are embedded into the source code.

There are 600+ color attributes (\x03 control codes) scattered all over the bot source. 

Unfortunately, some of the color combinations look terrible, and can be quite difficult to read (depending on the IRC client that you're using). 

For example, red on black, or even orange on black, have a very low contrast. So the output of some commands that use those combinations is quite hard to read. 

So let's say someone wanted to change those styles to more sensible ones (with better contrast and easier to read). As it is now, someone would have to make several hundred changes to the source to accomplish that. And even if that process could be automated, it doesn't make sense because those changes would be lost on the next bot update. 

A better way to handle this would be to define a set of default attributes, and then use those attributes in the source code instead of hard-coded color codes. For example:

```
CLR1 = "\x034,15"  # red on light gray
CLR2 = "\x036,15"  # purple on light gray
CLR3 = "\x031,8"  # black on yellow
```

Those attributes could be defined in duckhunt.cnf , and then in the source coude you'd use those attributes instead of hard-coding them. 

In this way, changing the color attributes would be trivial: just change some values in a configuration file and you are done. As a side effect, you would end up having a fully "themable" bot, which is something that most ops, channel owners and botmasters would welcome.

**Comment by m0de-60** [comment]
The color scheme is embedded for the purpose of preserving the original IRC DuckHunt game feel and color scheme. Most other users tell me its easy to read and understand. Color customization could be a future Super Duckhunt 2.0 feature, but as of right now there is no plans for overhauling color attributes.
