### ISSUE TITLE
Don't ask the player to reload when he has just done it

### ISSUE THREAD

**Issue by marthellius** [Neo-Coder-usa/super-duckhunt-beta#6]
Consider this game sequence:

```
[0:52:18] <Ducky> -.,¸¸.-·°'`'°·-.,¸¸.-·°'`'°·\_O<  QUACK
[0:52:41] <Elmer> !bang
[0:52:41] <Ducky> Elmer > *CLICK*    EMPTY MAGAZINE | Rounds: 0/7 | Magazines: 1/3
[0:52:46] <Elmer> !reload
[0:52:46] <Ducky> Elmer > *CLACK CLACK*     You reload. | Rounds: 7/7 | Magazines: 0/3
[0:52:49] <Elmer> !bang
[0:52:50] <Ducky> Elmer > *CLACK*     Your gun is jammed, you must reload to unjam it...
```

A duck appears in the room, and the player shoots but the gun is empty. 

So the bot asks him to reload, which he does swiftly, and shoots again... only to have the gun jammed and the bot asking to reload again (which he just did 3 seconds ago).

As you can see, this sequence that takes place over a few seconds doesn't make much sense. 

I'm not sure if this is completely random, or if the bot actually tracks the actions of each player over time. But if someone has just reloaded 5 seconds ago, then it shouldn't ask to reload again. 

Or... if you think that's actually a desired game mechanic, maybe you could add an "!unjam" command and ask for that one when the gun is jammed (keeping !reload for the times when the gun is actually empty).

**Comment by m0de-60** [comment]
Making gun perform better:
Earn xp and buy upgrades for your gun with !shop 7 (upgrades also clean the gun)
Clean gun with !shop 3 when reliability is below 70% for best results
Buy gun grease with !shop 6 (lowers wear on the gun) best purchase after cleaning the gun.

:)
